#!/bin/sh

DIR=$(dirname $0)

PYTHON="python3"

if test -f "${DIR}/gamess-setup-gui.py"; then
  ${PYTHON} ${DIR}/gamess-setup-gui.py ${HOME}
else
  ${PYTHON} /usr/share/gamess-setup/gamess-setup-gui.py ${HOME}
fi
